console.log("verificacion de tipo de datos")
console.log("typeof() dato")
console.log(typeof 42 +" 42")
console.log(typeof 'Veinticinco' + " 'Veinticinco'")
console.log(typeof -666 + " -666")
console.log(typeof true + " true")
console.log(typeof 0 + " 0")
console.log(typeof '' + " ''")
console.log(typeof null + " null")
console.log(typeof undefined + " undefined")
console.log(typeof FALSE + " FALSE")
console.log(typeof 23.4 + " 23.4")
console.log(typeof 37,8 + " 37,8")
console.log(typeof -51.6 + " -51.6")
console.log(typeof "" + ' ""')
console.log(typeof Object + " Object")
console.log(typeof -0.0 + " -0.0")